In [2]:
# requests library is used to make HTTP requests

import requests

In [16]:
url = "http://api.weatherapi.com/v1/current.json?key=7809c64d700d4c8cb86162822260205&q=Delhi&aqi=yes"

x = requests.get(url)
print(x.status_code)
print(x.text)

200
{"location":{"name":"Delhi","region":"Ontario","country":"Canada","lat":42.85,"lon":-80.5,"tz_id":"America/Toronto","localtime_epoch":1777740640,"localtime":"2026-05-02 12:50"},"current":{"last_updated_epoch":1777740300,"last_updated":"2026-05-02 12:45","temp_c":6.5,"temp_f":43.7,"is_day":1,"condition":{"text":"Overcast","icon":"//cdn.weatherapi.com/weather/64x64/day/122.png","code":1009},"wind_mph":9.6,"wind_kph":15.5,"wind_degree":278,"wind_dir":"W","pressure_mb":1016.0,"pressure_in":30.01,"precip_mm":0.0,"precip_in":0.0,"humidity":43,"cloud":0,"feelslike_c":3.5,"feelslike_f":38.4,"windchill_c":4.0,"windchill_f":39.1,"heatindex_c":6.8,"heatindex_f":44.3,"dewpoint_c":-3.0,"dewpoint_f":26.6,"vis_km":10.0,"vis_miles":6.0,"uv":3.4,"gust_mph":11.4,"gust_kph":18.4,"air_quality":{"co":146.837,"no2":1.737,"o3":86.0,"so2":1.337,"pm2_5":1.637,"pm10":1.837,"us-epa-index":1,"gb-defra-index":1},"short_rad":498.24,"diff_rad":148.4,"dni":484.56,"gti":300.0}}

In [17]:
data = x.json()
print(data)

{'location': {'name': 'Delhi', 'region': 'Ontario', 'country': 'Canada', 'lat': 42.85, 'lon': -80.5, 'tz_id': 'America/Toronto', 'localtime_epoch': 1777740640, 'localtime': '2026-05-02 12:50'}, 'current': {'last_updated_epoch': 1777740300, 'last_updated': '2026-05-02 12:45', 'temp_c': 6.5, 'temp_f': 43.7, 'is_day': 1, 'condition': {'text': 'Overcast', 'icon': '//cdn.weatherapi.com/weather/64x64/day/122.png', 'code': 1009}, 'wind_mph': 9.6, 'wind_kph': 15.5, 'wind_degree': 278, 'wind_dir': 'W', 'pressure_mb': 1016.0, 'pressure_in': 30.01, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 43, 'cloud': 0, 'feelslike_c': 3.5, 'feelslike_f': 38.4, 'windchill_c': 4.0, 'windchill_f': 39.1, 'heatindex_c': 6.8, 'heatindex_f': 44.3, 'dewpoint_c': -3.0, 'dewpoint_f': 26.6, 'vis_km': 10.0, 'vis_miles': 6.0, 'uv': 3.4, 'gust_mph': 11.4, 'gust_kph': 18.4, 'air_quality': {'co': 146.837, 'no2': 1.737, 'o3': 86.0, 'so2': 1.337, 'pm2_5': 1.637, 'pm10': 1.837, 'us-epa-index': 1, 'gb-defra-index': 1}, 'short_rad': 498.24, 'diff_rad': 148.4, 'dni': 484.56, 'gti': 300.0}}

In [18]:
city  = data['location']['name']
print(city)

Delhi

In [19]:
details = data['current']['condition']['text']
print(details)

Overcast

In [20]:
air = data['current']['air_quality']
print(air)

{'co': 146.837, 'no2': 1.737, 'o3': 86.0, 'so2': 1.337, 'pm2_5': 1.637, 'pm10': 1.837, 'us-epa-index': 1, 'gb-defra-index': 1}

In [21]:
city = data["location"]["name"]
region = data["location"]["region"]

temp = data["current"]["temp_c"]
humidity = data["current"]["humidity"]
wind_speed = data["current"]["wind_kph"]

condition = data["current"]["condition"]["text"]
air_quality = data["current"]["air_quality"]["pm2_5"]

print(f"City: {city}, Region: {region}")
print(f"Temperature: {temp}°C, Humidity: {humidity}%, Wind Speed: {wind_speed} kph")
print(f"Condition: {condition}, Air Quality (PM2.5): {air_quality}")

City: Delhi, Region: Ontario
Temperature: 6.5°C, Humidity: 43%, Wind Speed: 15.5 kph
Condition: Overcast, Air Quality (PM2.5): 1.637

In [22]:
# make it in a dictonary like foramt
weather_data = {
    "city": city,
    "region": region,
    "temperature_c": temp,
    "humidity": humidity,
    "wind_speed_kph": wind_speed,
    "condition": condition,
    "air_quality_pm2_5": air_quality
}

In [23]:
import pandas as pd

df = pd.DataFrame([weather_data])

print(df)

    city   region  temperature_c  humidity  wind_speed_kph condition  \
0  Delhi  Ontario            6.5        43            15.5  Overcast

   air_quality_pm2_5
0              1.637

In [ ]:
# save it to csv format and it rewite the original one
df.to_csv("Ranchi_weather.csv", index = False)

In [ ]:
# this will append every new data to the existing csv file without overwriting it
df.to_csv("Ranchi_weather_clean.csv", mode='a', header=False, index=False)

In [26]:
cities = ["Delhi", "Mumbai", "Bangalore", "Kolkata"]

In [30]:
import requests

all_data = []

for city in cities:
    url = f"http://api.weatherapi.com/v1/current.json?key=7809c64d700d4c8cb86162822260205&q={city}&aqi=yes"
    
    response = requests.get(url)
    data = response.json()

    clean_data = {
        "city": data["location"]["name"],
        "temp": data["current"]["temp_c"],
        "humidity": data["current"]["humidity"],
        "condition": data["current"]["condition"]["text"]
    }

    all_data.append(clean_data)
    
print(all_data)

[{'city': 'Delhi', 'temp': 6.5, 'humidity': 43, 'condition': 'Overcast'}, {'city': 'Mumbai', 'temp': 30.4, 'humidity': 75, 'condition': 'Mist'}, {'city': 'Bangalore', 'temp': 28.1, 'humidity': 66, 'condition': 'Partly cloudy'}, {'city': 'Kolkata', 'temp': 23.1, 'humidity': 94, 'condition': 'Mist'}]

In [33]:
import pandas as pd

df = pd.DataFrame(all_data)

print(df)

        city  temp  humidity      condition
0      Delhi   6.5        43       Overcast
1     Mumbai  30.4        75           Mist
2  Bangalore  28.1        66  Partly cloudy
3    Kolkata  23.1        94           Mist

In [34]:
df.to_csv("multiple_cities_weather.csv",index=False)

In [35]:
# loading dataset

new = pd.read_csv("multiple_cities_weather.csv")

new.head()

        city  temp  humidity      condition
0      Delhi   6.5        43       Overcast
1     Mumbai  30.4        75           Mist
2  Bangalore  28.1        66  Partly cloudy
3    Kolkata  23.1        94           Mist

In [36]:
new.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       4 non-null      str
 1   temp       4 non-null      float64
 2   humidity   4 non-null      int64
 3   condition  4 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 316.0 bytes

In [37]:
hot_cities = new[new["temp"] > 30]
print(hot_cities)

     city  temp  humidity condition
1  Mumbai  30.4        75      Mist

In [38]:
hot_humid = df[(df["temp"] > 30) & (df["humidity"] > 70)]

print(hot_humid)

     city  temp  humidity condition
1  Mumbai  30.4        75      Mist

In [40]:
# sorting the data by temperature in descending order
sorts = new.sort_values(by="temp",ascending=False)
print(sorts)

        city  temp  humidity      condition
1     Mumbai  30.4        75           Mist
2  Bangalore  28.1        66  Partly cloudy
3    Kolkata  23.1        94           Mist
0      Delhi   6.5        43       Overcast

In [ ]:
df["heatwave"] = (df["temp"] > 35) & (df["humidity"] < 50)
print(df)

df.to_csv("latest_dataset.csv", inplace=True)

        city  temp  humidity      condition  heatwave
0      Delhi   6.5        43       Overcast     False
1     Mumbai  30.4        75           Mist     False
2  Bangalore  28.1        66  Partly cloudy     False
3    Kolkata  23.1        94           Mist     False

TypeError: NDFrame.to_csv() got an unexpected keyword argument 'inplace'

In [42]:
new.head()

        city  temp  humidity      condition
0      Delhi   6.5        43       Overcast
1     Mumbai  30.4        75           Mist
2  Bangalore  28.1        66  Partly cloudy
3    Kolkata  23.1        94           Mist